import { createFileRoute } from "@tanstack/react-router";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { toast } from "sonner";
import { AdminShell, EmptyState, useAdminReady } from "@/components/AdminShell";
import { Button } from "@/components/ui/button";
import { deleteComment, deleteReport, fetchAllComments, fetchAllReports, setCommentApproval, setReportResolved } from "@/lib/moderation";
import { formatBnDate } from "@/lib/mtv";

export const Route = createFileRoute("/admin/moderation")({ head: () => ({ meta: [{ title: "মন্তব্য ও রিপোর্ট — MOHAKAL TELEVISION" }, { name: "description", content: "সংবাদের মন্তব্য ও রিপোর্ট পর্যালোচনা।" }, { property: "og:title", content: "মন্তব্য ও রিপোর্ট" }, { property: "og:description", content: "সংবাদের মন্তব্য ও রিপোর্ট পর্যালোচনা।" }, { property: "og:type", content: "website" }, { name: "twitter:card", content: "summary" }, { name: "robots", content: "noindex" }] }), component: ModerationPage });

function ModerationPage() {
  const enabled = useAdminReady(); const qc = useQueryClient();
  const { data: comments = [], isLoading: commentsLoading } = useQuery({ queryKey: ["admin-comments"], enabled, queryFn: fetchAllComments });
  const { data: reports = [], isLoading: reportsLoading } = useQuery({ queryKey: ["admin-reports"], enabled, queryFn: fetchAllReports });
  const refresh = () => { void qc.invalidateQueries({ queryKey: ["admin-comments"] }); void qc.invalidateQueries({ queryKey: ["admin-reports"] }); };
  const changeComment = useMutation({ mutationFn: ({ id, approved }: { id: string; approved: boolean }) => setCommentApproval(id, approved), onSuccess: refresh, onError: () => toast.error("হালনাগাদ ব্যর্থ") });
  const removeComment = useMutation({ mutationFn: deleteComment, onSuccess: refresh, onError: () => toast.error("মুছে ফেলা যায়নি") });
  const changeReport = useMutation({ mutationFn: ({ id, resolved }: { id: string; resolved: boolean }) => setReportResolved(id, resolved), onSuccess: refresh, onError: () => toast.error("হালনাগাদ ব্যর্থ") });
  const removeReport = useMutation({ mutationFn: deleteReport, onSuccess: refresh, onError: () => toast.error("মুছে ফেলা যায়নি") });
  return <AdminShell title="মন্তব্য ও রিপোর্ট"><div className="grid min-w-0 gap-5 lg:grid-cols-2"><section className="min-w-0 rounded border border-border bg-card p-3 sm:p-4"><h2 className="mb-3 text-base font-bold">মন্তব্য</h2>{commentsLoading ? <p>লোড হচ্ছে...</p> : comments.length === 0 ? <EmptyState text="কোনো মন্তব্য নেই" /> : <ul className="divide-y divide-border">{comments.map((item) => <li key={item.id} className="min-w-0 py-3"><p className="break-words text-sm font-semibold">{item.author_name} · <span className={item.is_approved ? "text-status-published" : "text-status-pending"}>{item.is_approved ? "অনুমোদিত" : "অপেক্ষমাণ"}</span></p><p className="mt-1 whitespace-pre-wrap break-words text-sm">{item.body}</p><p className="mt-1 break-words text-xs text-muted-foreground">{item.news?.title ?? "সংবাদ"} · {formatBnDate(item.created_at)}</p><div className="mt-2 flex flex-wrap gap-2"><Button size="sm" variant={item.is_approved ? "outline" : "default"} onClick={() => changeComment.mutate({ id: item.id, approved: !item.is_approved })}>{item.is_approved ? "লুকান" : "অনুমোদন"}</Button><Button size="sm" variant="destructive" onClick={() => confirm("মন্তব্য মুছবেন?") && removeComment.mutate(item.id)}>মুছুন</Button></div></li>)}</ul>}</section><section className="min-w-0 rounded border border-border bg-card p-3 sm:p-4"><h2 className="mb-3 text-base font-bold">রিপোর্ট</h2>{reportsLoading ? <p>লোড হচ্ছে...</p> : reports.length === 0 ? <EmptyState text="কোনো রিপোর্ট নেই" /> : <ul className="divide-y divide-border">{reports.map((item) => <li key={item.id} className="min-w-0 py-3"><p className="break-words text-sm font-semibold">{item.reason} · <span className={item.is_resolved ? "text-status-published" : "text-status-rejected"}>{item.is_resolved ? "সমাধান হয়েছে" : "খোলা"}</span></p><p className="mt-1 whitespace-pre-wrap break-words text-sm">{item.details || "বিস্তারিত দেওয়া হয়নি"}</p><p className="mt-1 break-all text-xs text-muted-foreground">{item.news?.title ?? "সংবাদ"} · {item.contact || "যোগাযোগ নেই"} · {formatBnDate(item.created_at)}</p><div className="mt-2 flex flex-wrap gap-2"><Button size="sm" variant={item.is_resolved ? "outline" : "default"} onClick={() => changeReport.mutate({ id: item.id, resolved: !item.is_resolved })}>{item.is_resolved ? "পুনরায় খুলুন" : "সমাধান"}</Button><Button size="sm" variant="destructive" onClick={() => confirm("রিপোর্ট মুছবেন?") && removeReport.mutate(item.id)}>মুছুন</Button></div></li>)}</ul>}</section></div></AdminShell>;
}