/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as DistrictRouteImport } from './routes/district'
import { Route as EpaperRouteImport } from './routes/epaper'
import { Route as LatestRouteImport } from './routes/latest'
import { Route as SearchRouteImport } from './routes/search'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminAdsRouteImport } from './routes/admin.ads'
import { Route as AdminCategoriesRouteImport } from './routes/admin.categories'
import { Route as AdminLocationsRouteImport } from './routes/admin.locations'
import { Route as AdminLoginRouteImport } from './routes/admin.login'
import { Route as AdminLogsRouteImport } from './routes/admin.logs'
import { Route as AdminMediaRouteImport } from './routes/admin.media'
import { Route as AdminModerationRouteImport } from './routes/admin.moderation'
import { Route as AdminPhotoCardsRouteImport } from './routes/admin.photo-cards'
import { Route as AdminRepresentativesRouteImport } from './routes/admin.representatives'
import { Route as AdminSettingsRouteImport } from './routes/admin.settings'
import { Route as AdminUsersRouteImport } from './routes/admin.users'
import { Route as CategorySlugRouteImport } from './routes/category.$slug'
import { Route as NewsSlugRouteImport } from './routes/news.$slug'
import { Route as RepresentativeIndexRouteImport } from './routes/representative.index'
import { Route as RepresentativeLoginRouteImport } from './routes/representative.login'
import { Route as RepresentativeRegisterRouteImport } from './routes/representative.register'
import { Route as AdminNewsIndexRouteImport } from './routes/admin.news.index'
import { Route as AdminNewsIdRouteImport } from './routes/admin.news.$id'
import { Route as AdminNewsNewRouteImport } from './routes/admin.news.new'
import { Route as RepresentativeNewsIndexRouteImport } from './routes/representative.news.index'
import { Route as RepresentativeNewsNewRouteImport } from './routes/representative.news.new'
import { Route as ApiPublicMediaSplatRouteImport } from './routes/api/public/media/$'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const DistrictRoute = DistrictRouteImport.update({
  id: '/district',
  path: '/district',
  getParentRoute: () => rootRouteImport,
} as any)
const EpaperRoute = EpaperRouteImport.update({
  id: '/epaper',
  path: '/epaper',
  getParentRoute: () => rootRouteImport,
} as any)
const LatestRoute = LatestRouteImport.update({
  id: '/latest',
  path: '/latest',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAdsRoute = AdminAdsRouteImport.update({
  id: '/admin/ads',
  path: '/admin/ads',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCategoriesRoute = AdminCategoriesRouteImport.update({
  id: '/admin/categories',
  path: '/admin/categories',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLocationsRoute = AdminLocationsRouteImport.update({
  id: '/admin/locations',
  path: '/admin/locations',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin/login',
  path: '/admin/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLogsRoute = AdminLogsRouteImport.update({
  id: '/admin/logs',
  path: '/admin/logs',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminMediaRoute = AdminMediaRouteImport.update({
  id: '/admin/media',
  path: '/admin/media',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminModerationRoute = AdminModerationRouteImport.update({
  id: '/admin/moderation',
  path: '/admin/moderation',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminPhotoCardsRoute = AdminPhotoCardsRouteImport.update({
  id: '/admin/photo-cards',
  path: '/admin/photo-cards',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRepresentativesRoute = AdminRepresentativesRouteImport.update({
  id: '/admin/representatives',
  path: '/admin/representatives',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/admin/settings',
  path: '/admin/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/admin/users',
  path: '/admin/users',
  getParentRoute: () => rootRouteImport,
} as any)
const CategorySlugRoute = CategorySlugRouteImport.update({
  id: '/category/$slug',
  path: '/category/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsSlugRoute = NewsSlugRouteImport.update({
  id: '/news/$slug',
  path: '/news/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const RepresentativeIndexRoute = RepresentativeIndexRouteImport.update({
  id: '/representative/',
  path: '/representative/',
  getParentRoute: () => rootRouteImport,
} as any)
const RepresentativeLoginRoute = RepresentativeLoginRouteImport.update({
  id: '/representative/login',
  path: '/representative/login',
  getParentRoute: () => rootRouteImport,
} as any)
const RepresentativeRegisterRoute = RepresentativeRegisterRouteImport.update({
  id: '/representative/register',
  path: '/representative/register',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminNewsIndexRoute = AdminNewsIndexRouteImport.update({
  id: '/admin/news/',
  path: '/admin/news/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminNewsIdRoute = AdminNewsIdRouteImport.update({
  id: '/admin/news/$id',
  path: '/admin/news/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminNewsNewRoute = AdminNewsNewRouteImport.update({
  id: '/admin/news/new',
  path: '/admin/news/new',
  getParentRoute: () => rootRouteImport,
} as any)
const RepresentativeNewsIndexRoute = RepresentativeNewsIndexRouteImport.update({
  id: '/representative/news/',
  path: '/representative/news/',
  getParentRoute: () => rootRouteImport,
} as any)
const RepresentativeNewsNewRoute = RepresentativeNewsNewRouteImport.update({
  id: '/representative/news/new',
  path: '/representative/news/new',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicMediaSplatRoute = ApiPublicMediaSplatRouteImport.update({
  id: '/api/public/media/$',
  path: '/api/public/media/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/district': typeof DistrictRoute
  '/epaper': typeof EpaperRoute
  '/latest': typeof LatestRoute
  '/search': typeof SearchRoute
  '/admin/ads': typeof AdminAdsRoute
  '/admin/categories': typeof AdminCategoriesRoute
  '/admin/locations': typeof AdminLocationsRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/logs': typeof AdminLogsRoute
  '/admin/media': typeof AdminMediaRoute
  '/admin/moderation': typeof AdminModerationRoute
  '/admin/photo-cards': typeof AdminPhotoCardsRoute
  '/admin/representatives': typeof AdminRepresentativesRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/users': typeof AdminUsersRoute
  '/category/$slug': typeof CategorySlugRoute
  '/news/$slug': typeof NewsSlugRoute
  '/representative/login': typeof RepresentativeLoginRoute
  '/representative/register': typeof RepresentativeRegisterRoute
  '/admin/': typeof AdminIndexRoute
  '/representative/': typeof RepresentativeIndexRoute
  '/admin/news/$id': typeof AdminNewsIdRoute
  '/admin/news/new': typeof AdminNewsNewRoute
  '/representative/news/new': typeof RepresentativeNewsNewRoute
  '/admin/news/': typeof AdminNewsIndexRoute
  '/representative/news/': typeof RepresentativeNewsIndexRoute
  '/api/public/media/$': typeof ApiPublicMediaSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/district': typeof DistrictRoute
  '/epaper': typeof EpaperRoute
  '/latest': typeof LatestRoute
  '/search': typeof SearchRoute
  '/admin/ads': typeof AdminAdsRoute
  '/admin/categories': typeof AdminCategoriesRoute
  '/admin/locations': typeof AdminLocationsRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/logs': typeof AdminLogsRoute
  '/admin/media': typeof AdminMediaRoute
  '/admin/moderation': typeof AdminModerationRoute
  '/admin/photo-cards': typeof AdminPhotoCardsRoute
  '/admin/representatives': typeof AdminRepresentativesRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/users': typeof AdminUsersRoute
  '/category/$slug': typeof CategorySlugRoute
  '/news/$slug': typeof NewsSlugRoute
  '/representative/login': typeof RepresentativeLoginRoute
  '/representative/register': typeof RepresentativeRegisterRoute
  '/admin': typeof AdminIndexRoute
  '/representative': typeof RepresentativeIndexRoute
  '/admin/news/$id': typeof AdminNewsIdRoute
  '/admin/news/new': typeof AdminNewsNewRoute
  '/representative/news/new': typeof RepresentativeNewsNewRoute
  '/admin/news': typeof AdminNewsIndexRoute
  '/representative/news': typeof RepresentativeNewsIndexRoute
  '/api/public/media/$': typeof ApiPublicMediaSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/district': typeof DistrictRoute
  '/epaper': typeof EpaperRoute
  '/latest': typeof LatestRoute
  '/search': typeof SearchRoute
  '/admin/ads': typeof AdminAdsRoute
  '/admin/categories': typeof AdminCategoriesRoute
  '/admin/locations': typeof AdminLocationsRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/logs': typeof AdminLogsRoute
  '/admin/media': typeof AdminMediaRoute
  '/admin/moderation': typeof AdminModerationRoute
  '/admin/photo-cards': typeof AdminPhotoCardsRoute
  '/admin/representatives': typeof AdminRepresentativesRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/users': typeof AdminUsersRoute
  '/category/$slug': typeof CategorySlugRoute
  '/news/$slug': typeof NewsSlugRoute
  '/representative/login': typeof RepresentativeLoginRoute
  '/representative/register': typeof RepresentativeRegisterRoute
  '/admin/': typeof AdminIndexRoute
  '/representative/': typeof RepresentativeIndexRoute
  '/admin/news/$id': typeof AdminNewsIdRoute
  '/admin/news/new': typeof AdminNewsNewRoute
  '/representative/news/new': typeof RepresentativeNewsNewRoute
  '/admin/news/': typeof AdminNewsIndexRoute
  '/representative/news/': typeof RepresentativeNewsIndexRoute
  '/api/public/media/$': typeof ApiPublicMediaSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/contact'
    | '/district'
    | '/epaper'
    | '/latest'
    | '/search'
    | '/admin/ads'
    | '/admin/categories'
    | '/admin/locations'
    | '/admin/login'
    | '/admin/logs'
    | '/admin/media'
    | '/admin/moderation'
    | '/admin/photo-cards'
    | '/admin/representatives'
    | '/admin/settings'
    | '/admin/users'
    | '/category/$slug'
    | '/news/$slug'
    | '/representative/login'
    | '/representative/register'
    | '/admin/'
    | '/representative/'
    | '/admin/news/$id'
    | '/admin/news/new'
    | '/representative/news/new'
    | '/admin/news/'
    | '/representative/news/'
    | '/api/public/media/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contact'
    | '/district'
    | '/epaper'
    | '/latest'
    | '/search'
    | '/admin/ads'
    | '/admin/categories'
    | '/admin/locations'
    | '/admin/login'
    | '/admin/logs'
    | '/admin/media'
    | '/admin/moderation'
    | '/admin/photo-cards'
    | '/admin/representatives'
    | '/admin/settings'
    | '/admin/users'
    | '/category/$slug'
    | '/news/$slug'
    | '/representative/login'
    | '/representative/register'
    | '/admin'
    | '/representative'
    | '/admin/news/$id'
    | '/admin/news/new'
    | '/representative/news/new'
    | '/admin/news'
    | '/representative/news'
    | '/api/public/media/$'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/contact'
    | '/district'
    | '/epaper'
    | '/latest'
    | '/search'
    | '/admin/ads'
    | '/admin/categories'
    | '/admin/locations'
    | '/admin/login'
    | '/admin/logs'
    | '/admin/media'
    | '/admin/moderation'
    | '/admin/photo-cards'
    | '/admin/representatives'
    | '/admin/settings'
    | '/admin/users'
    | '/category/$slug'
    | '/news/$slug'
    | '/representative/login'
    | '/representative/register'
    | '/admin/'
    | '/representative/'
    | '/admin/news/$id'
    | '/admin/news/new'
    | '/representative/news/new'
    | '/admin/news/'
    | '/representative/news/'
    | '/api/public/media/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ContactRoute: typeof ContactRoute
  DistrictRoute: typeof DistrictRoute
  EpaperRoute: typeof EpaperRoute
  LatestRoute: typeof LatestRoute
  SearchRoute: typeof SearchRoute
  AdminAdsRoute: typeof AdminAdsRoute
  AdminCategoriesRoute: typeof AdminCategoriesRoute
  AdminLocationsRoute: typeof AdminLocationsRoute
  AdminLoginRoute: typeof AdminLoginRoute
  AdminLogsRoute: typeof AdminLogsRoute
  AdminMediaRoute: typeof AdminMediaRoute
  AdminModerationRoute: typeof AdminModerationRoute
  AdminPhotoCardsRoute: typeof AdminPhotoCardsRoute
  AdminRepresentativesRoute: typeof AdminRepresentativesRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminUsersRoute: typeof AdminUsersRoute
  CategorySlugRoute: typeof CategorySlugRoute
  NewsSlugRoute: typeof NewsSlugRoute
  RepresentativeLoginRoute: typeof RepresentativeLoginRoute
  RepresentativeRegisterRoute: typeof RepresentativeRegisterRoute
  AdminIndexRoute: typeof AdminIndexRoute
  RepresentativeIndexRoute: typeof RepresentativeIndexRoute
  AdminNewsIdRoute: typeof AdminNewsIdRoute
  AdminNewsNewRoute: typeof AdminNewsNewRoute
  RepresentativeNewsNewRoute: typeof RepresentativeNewsNewRoute
  AdminNewsIndexRoute: typeof AdminNewsIndexRoute
  RepresentativeNewsIndexRoute: typeof RepresentativeNewsIndexRoute
  ApiPublicMediaSplatRoute: typeof ApiPublicMediaSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/district': {
      id: '/district'
      path: '/district'
      fullPath: '/district'
      preLoaderRoute: typeof DistrictRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/epaper': {
      id: '/epaper'
      path: '/epaper'
      fullPath: '/epaper'
      preLoaderRoute: typeof EpaperRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/latest': {
      id: '/latest'
      path: '/latest'
      fullPath: '/latest'
      preLoaderRoute: typeof LatestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/ads': {
      id: '/admin/ads'
      path: '/admin/ads'
      fullPath: '/admin/ads'
      preLoaderRoute: typeof AdminAdsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/categories': {
      id: '/admin/categories'
      path: '/admin/categories'
      fullPath: '/admin/categories'
      preLoaderRoute: typeof AdminCategoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/locations': {
      id: '/admin/locations'
      path: '/admin/locations'
      fullPath: '/admin/locations'
      preLoaderRoute: typeof AdminLocationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/admin/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/logs': {
      id: '/admin/logs'
      path: '/admin/logs'
      fullPath: '/admin/logs'
      preLoaderRoute: typeof AdminLogsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/media': {
      id: '/admin/media'
      path: '/admin/media'
      fullPath: '/admin/media'
      preLoaderRoute: typeof AdminMediaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/moderation': {
      id: '/admin/moderation'
      path: '/admin/moderation'
      fullPath: '/admin/moderation'
      preLoaderRoute: typeof AdminModerationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/photo-cards': {
      id: '/admin/photo-cards'
      path: '/admin/photo-cards'
      fullPath: '/admin/photo-cards'
      preLoaderRoute: typeof AdminPhotoCardsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/representatives': {
      id: '/admin/representatives'
      path: '/admin/representatives'
      fullPath: '/admin/representatives'
      preLoaderRoute: typeof AdminRepresentativesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/admin/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/admin/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/category/$slug': {
      id: '/category/$slug'
      path: '/category/$slug'
      fullPath: '/category/$slug'
      preLoaderRoute: typeof CategorySlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/news/$slug': {
      id: '/news/$slug'
      path: '/news/$slug'
      fullPath: '/news/$slug'
      preLoaderRoute: typeof NewsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/representative/': {
      id: '/representative/'
      path: '/representative'
      fullPath: '/representative/'
      preLoaderRoute: typeof RepresentativeIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/representative/login': {
      id: '/representative/login'
      path: '/representative/login'
      fullPath: '/representative/login'
      preLoaderRoute: typeof RepresentativeLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/representative/register': {
      id: '/representative/register'
      path: '/representative/register'
      fullPath: '/representative/register'
      preLoaderRoute: typeof RepresentativeRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/news/': {
      id: '/admin/news/'
      path: '/admin/news'
      fullPath: '/admin/news/'
      preLoaderRoute: typeof AdminNewsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/news/$id': {
      id: '/admin/news/$id'
      path: '/admin/news/$id'
      fullPath: '/admin/news/$id'
      preLoaderRoute: typeof AdminNewsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/news/new': {
      id: '/admin/news/new'
      path: '/admin/news/new'
      fullPath: '/admin/news/new'
      preLoaderRoute: typeof AdminNewsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/representative/news/': {
      id: '/representative/news/'
      path: '/representative/news'
      fullPath: '/representative/news/'
      preLoaderRoute: typeof RepresentativeNewsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/representative/news/new': {
      id: '/representative/news/new'
      path: '/representative/news/new'
      fullPath: '/representative/news/new'
      preLoaderRoute: typeof RepresentativeNewsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/media/$': {
      id: '/api/public/media/$'
      path: '/api/public/media/$'
      fullPath: '/api/public/media/$'
      preLoaderRoute: typeof ApiPublicMediaSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ContactRoute: ContactRoute,
  DistrictRoute: DistrictRoute,
  EpaperRoute: EpaperRoute,
  LatestRoute: LatestRoute,
  SearchRoute: SearchRoute,
  AdminAdsRoute: AdminAdsRoute,
  AdminCategoriesRoute: AdminCategoriesRoute,
  AdminLocationsRoute: AdminLocationsRoute,
  AdminLoginRoute: AdminLoginRoute,
  AdminLogsRoute: AdminLogsRoute,
  AdminMediaRoute: AdminMediaRoute,
  AdminModerationRoute: AdminModerationRoute,
  AdminPhotoCardsRoute: AdminPhotoCardsRoute,
  AdminRepresentativesRoute: AdminRepresentativesRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminUsersRoute: AdminUsersRoute,
  CategorySlugRoute: CategorySlugRoute,
  NewsSlugRoute: NewsSlugRoute,
  RepresentativeLoginRoute: RepresentativeLoginRoute,
  RepresentativeRegisterRoute: RepresentativeRegisterRoute,
  AdminIndexRoute: AdminIndexRoute,
  RepresentativeIndexRoute: RepresentativeIndexRoute,
  AdminNewsIdRoute: AdminNewsIdRoute,
  AdminNewsNewRoute: AdminNewsNewRoute,
  RepresentativeNewsNewRoute: RepresentativeNewsNewRoute,
  AdminNewsIndexRoute: AdminNewsIndexRoute,
  RepresentativeNewsIndexRoute: RepresentativeNewsIndexRoute,
  ApiPublicMediaSplatRoute: ApiPublicMediaSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
